commitizen:
  name: cz_customize
  version_files:
    - README.md:badge/version-
    - "bootstrap.sh:# Version: "
  tag_format: v$version
  version_scheme: semver
  version_provider: scm
  update_changelog_on_bump: true
  major_version_zero: true
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  changelog_start_rev: null
  bump_message: "bump: version $current_version → $new_version [skip ci]"
  customize:
    message_template: "{{change_type}}{% if scope %}({{scope}}){% endif %}: [gh-{{issue}}] {{message}}"
    example: "feat(api): [gh-42] add new endpoint for user authentication"
    schema: "<type>(<scope>): [gh-<issue>] <subject>"
    schema_pattern: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|devcontainer|conf)(\\(\\w+\\))?: \\[gh-\\d+\\] .+$"
    bump_pattern: "^(feat|fix|perf|refactor|conf)"
    bump_map:
      feat: MINOR
      fix: PATCH
      perf: PATCH
      refactor: PATCH
      conf: PATCH
    change_type_order:
      - feat
      - fix
      - refactor
      - perf
      - build
      - ci
      - docs
      - style
      - test
      - chore
      - devcontainer
      - conf
    commit_parser: "^(?P<change_type>feat|fix|docs|style|refactor|perf|test|build|ci|chore|devcontainer|conf)(?:\\((?P<scope>[^)]+)\\))?!?: \\[gh-(?P<issue>\\d+)\\] (?P<message>.+)$"
    changelog_pattern: "^(feat|fix|refactor|perf|build|ci|docs|style|test|chore|devcontainer|conf)(\\(.+\\))?: \\[gh-\\d+\\]"
    change_type_map:
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      perf: Performance Improvements
      build: Build System
      ci: Continuous Integration
      docs: Documentation
      style: Code Style
      test: Tests
      chore: Chores
      devcontainer: Development Container
      conf: Configuration
