commitizen:
  name: cz_customize
  version_files:
    - README.md:badge/version-
    - "bootstrap.sh:# Version: "
  tag_format: v$version
  version_scheme: semver
  version_provider: scm
  update_changelog_on_bump: true
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  bump_message: "bump: version $current_version → $new_version [skip ci]"
  customize:
    bump_pattern: "^((BREAKING[\\-\\ ]CHANGE|\\w+)(\\(.+\\))?!?):"
    bump_map:
      ^.+!$: MAJOR
      ^BREAKING[\-\ ]CHANGE: MAJOR
      ^feat: MINOR
      ^fix: PATCH
      ^refactor: PATCH
      ^perf: PATCH
    change_type_order: ["BREAKING CHANGE", "Feat", "Fix", "Conf", "Refactor", "Perf", "Chore", "Docs", "Style", "Test", "Build", "CICD", "Devcontainer"]
    message_template: "{{prefix}}{% if scope %}({{scope}}){% endif %}{% if is_breaking_change %}!{% endif %}: [gh-{{issue}}] {{subject}}{% if body %}\n\n{{body}}{% endif %}{% if is_breaking_change and footer %}\n\nBREAKING CHANGE: {{footer}}{% endif %}{% if not is_breaking_change and footer %}\n\n{{footer}}{% endif %}"
    example: "feat(api)!: [gh-42] add new endpoint requiring authentication"
    schema: "<type>(<scope>)[!]: [gh-<issue>] <subject>\n<BLANK LINE>\n<body>\n<BLANK LINE>\n(BREAKING CHANGE: )<footer>"
    schema_pattern: '(?s)(build|bump|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\S+\))?!?: \[gh-\d+\] [^\n\r]+((\n\n.*)|(\s*))?$'
    questions:
      - type: list
        name: prefix
        message: "Select the type of change you are committing"
        choices:
          - value: feat
            name: "feat: A new feature"
          - value: fix
            name: "fix: A bug fix"
          - value: docs
            name: "docs: Documentation only changes"
          - value: style
            name: "style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
          - value: refactor
            name: "refactor: A code change that neither fixes a bug nor adds a feature"
          - value: perf
            name: "perf: A code change that improves performance"
          - value: test
            name: "test: Adding missing or correcting existing tests"
          - value: build
            name: "build: Changes that affect the build system or external dependencies (example scopes: pip, docker, npm)"
          - value: cicd
            name: "cicd: Changes to CI/CD configuration"
          - value: chore
            name: "chore: Other changes that don't modify src or test files"
          - value: devcontainer
            name: "devcontainer: Development container changes"
          - value: conf
            name: "conf: Configuration changes"
      - type: input
        name: scope
        message: "What is the scope of this change? (class or file name): (press [enter] to skip)"
      - type: input
        name: issue
        message: "GitHub issue number (e.g., 42 for gh-42):"
      - type: input
        name: subject
        message: "Write a short and imperative summary of the code changes: (lower case and no period)"
      - type: input
        name: body
        message: "Provide additional contextual information about the code changes: (press [enter] to skip)"
        multiline: true
      - type: confirm
        name: is_breaking_change
        message: "Is this a BREAKING CHANGE? Correlates with MAJOR in SemVer"
        default: false
      - type: input
        name: footer
        message: "Footer. Information about Breaking Changes and reference issues that this commit closes: (press [enter] to skip)"
    commit_parser: "^(?P<change_type>feat|fix|docs|style|refactor|perf|test|build|cicd|chore|devcontainer|conf)(?:\\((?P<scope>[^)]+)\\))?(?P<breaking>!)?:?\\s*\\[gh-(?P<issue>\\d+)\\]\\s*(?P<message>.+?)(?:\\n\\nBREAKING CHANGE:\\s*(?P<breaking_description>.+))?$"
    changelog_pattern: "^(feat|fix|refactor|perf|docs|chore|conf)(\\(.+\\))?: \\[gh-\\d+\\]"
    change_type_map:
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      perf: Performance Improvements
      docs: Documentation
      chore: Chores
      conf: Configuration
